# -*- coding: utf-8 -*-
"""16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brcrDXgjBUfu-0mIevuf9_e2g80xOQtT
"""

def Ebarat2(A,B,C):
  return True
A=input()
B=input()
C=input()
print(Ebarat2(A,B,C))

def Ebarat3(A,B,C,D):
  if(((A=="False") and (B=="True") and (C=="True") and (D=="True")) or ((A=="True") and (B=="False") and (C=="True") and (D=="True"))):
    print("True")
  else:
    print("False")
A=input()
B=input()
C=input()
D=input()
Ebarat3(A,B,C,D)

def Ebarat1(A,B,C):
  if(((A=="False") and (B=="False") and (C=="False")) or ((A=="True") and (B=="False") and (C=="False")) or ((A==True) and (B=="True") and (C=="False")) or ((A=="True") and (B=="True") and (C=="True"))):
    print("True")
  else:
    print("False")
A=input()
B=input()
C=input()
Ebarat1(A,B,C)