# -*- coding: utf-8 -*-
"""15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o9FxdpeEFyKnyQ8sFgUkSb7M6CQrCQ03
"""

num1=input()
num2=input()
def DTAnd(num1,num2):
   if (num1=="False"):
    print("False")
   else:
     print("fuck")
     if(num2=="False"):
      print("False")
     else:
      print("true")

DTAnd(num1,num2)

def DTOr(numor1,numor2):
  if(numor1=="True"):
    print("True")
  else:
    if(numor2=="True"):
      print("True")
    else:
      print("False")


numor1=input()
numor2=input()
DTOr(numor1,numor2)

def DTNot(numn1):
  if(numn1=="True"):
    print("False")
  else:
    print("True")

numn1=input()
DTNot(numn1)

numN1=input()
numN2=input()
def DTNand(numN1,numN2):
   if (numN1=="False"):
    print("True")
   else:
     if(numN2=="False"):
      print("True")
     else:
      print("False")

DTNand(numN1,numN2)

def DTNor(numnor1,numnor2):
  if(numnor1=="True"):
    print("False")
  else:
    if(numnor2=="True"):
      print("False")
    else:
      print("True")


numnor1=input()
numnor2=input()
DTNor(numnor1,numnor2)

def DTXOR(numx1,numx2):
  if(((numx1=="False") and (numx2=="True")) or ((numx1=="True") and (numx2=="False")) ):
    print("True")
  elif (((numx1=="False") and (numx2=="False")) or ((numx1=="True") and (numx2=="True"))) :
    print("False")

numx1=input()
numx2=input()
DTXOR(numx1,numx2)