# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fEXj3EVn19nIaJ1FhHo_z-bpSm7u2Irg
"""

!pip3 install wordcloud-fa

from wordcloud_fa import WordCloudFa
wc = WordCloudFa()

with open('news.txt', 'r') as file:
    text = file.read()

    wc = WordCloudFa(width=1000, height=600)
    wc = WordCloudFa(background_color="blue")

word_cloud = wc.generate(text)

image = word_cloud.to_image()
image.show()

image.save('news.png')