# -*- coding: utf-8 -*-
"""18Entropy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4XFgr7n-ZqBYosHwJLdvpmxxqmAMFXz
"""

import math
def Entropy(Ppositive,Pnegative):
  entropy=((-1)*(((Ppositive)*(math.log(Ppositive,(2)))) + ((Pnegative)*(math.log(Pnegative,(2))))))
  print(entropy)
Ppositive=float(input())
Pnegative=float(input())
Entropy(Ppositive,Pnegative)