# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BNNYAPk4y0vJiNpko2BU_Zq_8JrzuTC0
"""

#import libraries
import matplotlib.pyplot 
import numpy as np

#define the points and dist
points = np.random.random_sample(size = (100,2))*50
n43th = points[43-1] 
dist = np.linalg.norm(points - n43th, axis=1)
neighbors = dist.argsort()[:4]

#draw the diagram with scatter
matplotlib.pyplot.scatter(points[:,0],points[:,1],c="b")
matplotlib.pyplot.scatter(points[neighbors][:,0],points[neighbors][:,1],c="r")
matplotlib.pyplot.scatter(points[42,0],points[42,1],c="y")
matplotlib.pyplot.show()

#calculate the value of the points
for i in range(3):
    print("point {} : x: {:.4f} y: {:.3f}".format(i+1,points[neighbors[i]][0], points[neighbors[i]][1]))