# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WPKeTsS3XuEa8y4ax6qbE53pgwVpMNGA
"""

from numpy.lib.function_base import piecewise
import numpy as np
points = np.random.randint(low = 1 , high=50 , size=(100,2))
print(points)

